UCMRS/UCMRS/Controllers/ProviderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UCMRS.Models.DB;
using UCMRS.Models.UnivContext;

namespace UCMRS.Controllers
{
    public class ProviderController : Controller
    {
        private UniContext db = new UniContext(); 
        // GET: Provider
        public ActionResult Index()
        {
            return View();
        }

        #region Semester

        public ActionResult SemesterIndex()
        {
            try
            {
                var semesters = db.Semesters.ToList();
                if (semesters != null)
                {
                    return View(semesters);
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
            return RedirectToAction("");
        }

        /// <summary>
        /// Load input form for Semester
        /// </summary>
        /// <returns></returns>
        public ActionResult SaveSemester()
        {
            try
            {
                return View();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                throw;
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SaveSemester(Semester semester)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Semesters.Add(semester);
                    db.SaveChanges();
                    return RedirectToAction("SemesterIndex");
                }
                return RedirectToAction("SaveSemester");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                throw;
            }
        }
        #endregion

        #region Designation

        public ActionResult IndexDesignation()
        {
            try
            {
                var designation = db.Designations.ToList();
                if (designation.Any())
                {
                    return View(designation);
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
            return RedirectToAction("");
        }

        /// <summary>
        /// Load input form for Semester
        /// </summary>
        /// <returns></returns>
        public ActionResult SaveDesignation()
        {
            try
            {
                return View();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                throw;
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SaveDesignation(Designation designation)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Designations.Add(designation);
                    db.SaveChanges();
                    return RedirectToAction("IndexDesignation");
                }
                return RedirectToAction("SaveSemester");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                throw;
            }
        }

        #endregion

        #region Rooms

        public ActionResult IndexRoom()
        {
            try
            {
                var rooms = db.Rooms.ToList();
                if (rooms.Any())
                {
                    return View(rooms);
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
            return RedirectToAction("");
        }

        /// <summary>
        /// Load input form for Semester
        /// </summary>
        /// <returns></returns>
        public ActionResult SaveRoom()
        {
            try
            {
                return View();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                throw;
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SaveRoom(Room room)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Rooms.Add(room);
                    db.SaveChanges();
                    return RedirectToAction("IndexRoom");
                }
                return RedirectToAction("SaveRoom");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                throw;
            }
        }

        #endregion
    }
}

UCMRS/UCMRS/Controllers/UCRMSController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using UCMRS.Models;
using UCMRS.Models.Entity;
using UCMRS.Models.UnivContext;
using UCMRS.Models.View;

namespace UCMRS.Controllers
{
    public class UCRMSController : Controller
    {
        private UniContext db = new UniContext();
        private DropDownData d = new DropDownData();

        #region Department Settings...

        // GET: UCRMS
        public ActionResult Index()
        {
            try
            {
                return View(db.Departments.ToList());
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
        }

        // GET: UCRMS/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department department = db.Departments.Find(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            return View(department);
        }

        // GET: UCRMS/Create
        public ActionResult AddDepartment()
        {
            return View();
        }

        // POST: UCRMS/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddDepartment([Bind(Include = "Id,Code,Name")] Department department)
        {
            if (ModelState.IsValid)
            {
                if (!db.Departments.Any(d => d.Code == department.Code))
                {
                    db.Departments.Add(department);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("AddDepartment");
                }
            }
            return View();
        }

        // GET: UCRMS/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department department = db.Departments.Find(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            return View(department);
        }

        // POST: UCRMS/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Code,Name")] Department department)
        {
            if (ModelState.IsValid)
            {
                db.Entry(department).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(department);
        }

        // GET: UCRMS/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department department = db.Departments.Find(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            return View(department);
        }

        // POST: UCRMS/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Department department = db.Departments.Find(id);
            db.Departments.Remove(department);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        #endregion
        
        #region Course Settings

        
        // GET: UCRMS
        public async Task<ActionResult> IndexCourse()
        {
            VM_Course vmCourse = new VM_Course();
            await Task.Run(() => vmCourse.GetCourseList());
            return View(vmCourse);
        }

        // GET: UCRMS/Details/5
        public ActionResult CourseDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VM_Course course = new VM_Course();
            
            if (course.GetCourse(id) == null)
            {
                return HttpNotFound();
            }
            
            return View(course.GetCourse(id.Value));
        }

        // GET: UCRMS/Create
        public ActionResult CreateCourse()
        {
            ViewBag.Dept = new SelectList(db.Departments.ToList().OrderBy(s=>s.Id),"Id","Name");
            ViewBag.Semesters = new SelectList(db.Semesters.ToList().OrderBy(s=>s.Id),"Id","Name");
             return View();
        }

        // POST: UCRMS/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateCourse(Course course)
        {
            if (ModelState.IsValid)
            {
                ViewBag.Dept = new SelectList(db.Departments.ToList().OrderBy(s=>s.Id),"Id","Name");
                ViewBag.Semesters = new SelectList(db.Semesters.ToList().OrderBy(s=>s.Id),"Id","Name");
                if (!db.Courses.Any(n => n.Code == course.Code && n.Name == course.Name))
                {
                    db.Courses.Add(course);
                    db.SaveChanges();
                    return RedirectToAction("IndexCourse");
                }
                else
                {
                    return RedirectToAction("CreateCourse");
                }
                
            }
            return View();
        }

        // GET: UCRMS/Edit/5
        public ActionResult EditCourse(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course Course = db.Courses.Find(id);
            if (Course == null)
            {
                return HttpNotFound();
            }
            ViewBag.Dept = new SelectList(db.Departments.ToList().OrderBy(s=>s.Id),"Id","Name");
            ViewBag.Semesters = new SelectList(db.Semesters.ToList().OrderBy(s=>s.Id),"Id","Name");
            return View(Course);
        }

        // POST: UCRMS/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditCourse(Course Course)
        {
            if (ModelState.IsValid)
            {
                ViewBag.Dept = new SelectList(db.Departments.ToList().OrderBy(s=>s.Id),"Id","Name");
                ViewBag.Semesters = new SelectList(db.Semesters.ToList().OrderBy(s=>s.Id),"Id","Name");
                db.Entry(Course).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("IndexCourse");
            }
            return View(Course);
        }

        // GET: UCRMS/Delete/5
        public ActionResult DeleteCourse(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: UCRMS/Delete/5
        [HttpPost, ActionName("DeleteCourse")]
        [ValidateAntiForgeryToken]
        public ActionResult CourseDeleteConfirmed(int id)
        {
            Course course = db.Courses.Find(id);
            db.Courses.Remove(course);
            db.SaveChanges();
            return RedirectToAction("IndexCourse");
        }
        
        #endregion

        #region Teacher Settings

        /// <summary>
        /// Teacher List View------
        /// </summary>
        /// <returns></returns>
        public async Task<ActionResult> IndexTeacher()
        {
            try
            {
                VM_Teacher vmTeacher = new VM_Teacher();
                await Task.Run(() => vmTeacher.GetTeacherList());
                return View(vmTeacher);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
        }

        /// <summary>
        /// Load Form for Teacher Entry
        /// </summary>
        /// <returns></returns>
        public ActionResult AddTeacherInfo()
        {
            try
            {
                ViewBag.Department = new SelectList(d.GetDeptList(), "Value", "Text");
                ViewBag.Designation = new SelectList(d.GetDesignationList(), "Value", "Text");
                return View();
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
        }

        /// <summary>
        /// Submit form for Teacher Infomation
        /// </summary>
        /// <param name="vmTeacher"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]

UCMRS/UCMRS/Views/Shared/_FlashMessage.cshtml
@if (Session["success_div"] != null && Session["success_div"].ToString() == "true")
{
    Session["success_div"] = null;
    <text>
        <script>
        swal.setDefaults({
            confirmButtonColor: '#9CD159',
            showLoaderOnConfirm: true,
            allowOutsideClick: true
        });
        swal({
            title: 'Success!',
            text: '@Session["success_msg"].ToString()',
            html: '@Session["success_msg"].ToString()',
            type: 'success'
        });
        </script>
    </text>
    Session["success_msg"] = null;
}
else if (Session["error_div"] != null && Session["error_div"].ToString() == "true")
{
    Session["error_div"] = null;
    <text>
        <script>
        swal.setDefaults({
            confirmButtonColor: '#9CD159',
            showLoaderOnConfirm: true,
            allowOutsideClick: true
        });
        swal({
            title: 'ERROR!',
            text: '@Session["error_msg"].ToString()',
            html: '@Session["error_msg"].ToString()',
            type: 'error'
        });
        </script>
    </text>
    Session["error_msg"] = null;
}
else if (Session["warning_div"] != null && Session["warning_div"].ToString() == "true")
{
    Session["warning_div"] = null;
    <text>
        <script>
        swal.setDefaults({
            confirmButtonColor: '#9CD159',
            showLoaderOnConfirm: true,
            allowOutsideClick: true
        });
        swal({
            title: 'WARNING!',
            text: '@Session["warning_msg"].ToString()',
            html: '@Session["warning_msg"].ToString()',
            type: 'warning'
        });
        </script>
    </text>
    Session["warning_msg"] = null;
}
else if (Session["info_div"] != null && Session["info_div"].ToString() == "true")
{
    Session["info_div"] = null;
    <text>
        <script>
        swal.setDefaults({
            confirmButtonColor: '#9CD159',
            showLoaderOnConfirm: true,
            allowOutsideClick: true
        });
        swal({
            title: 'INFO!',
            text: '@Session["info_msg"].ToString()',
            html: '@Session["info_msg"].ToString()',
            type: 'info'
        });
        </script>
    </text>
    Session["info_msg"] = null;
}

UCMRS/UCMRS/Views/Shared/_Layout.cshtml
@*<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title - University Course and Result Management System</title>
        <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
        <script src="~/Scripts/modernizr-2.8.3.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <div class="row col-md-12">
                <nav class="navbar navbar-expand bg-dark">
                    <div class="container">

                        <div class="navbar-brand">
                            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="icon-bar">Student</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            @Html.ActionLink("University Course and Result Management System", "Index", "Home", null, new { @class = "navbar-brand btn-info btn-toolbar" })

                        </div>

                        <div class="navbar-collapse collapse">
                            <ul class="nav navbar-nav">
                                <li>@Html.ActionLink("Department", "Index", "UCRMS", null, new { @class = "btn-info " })</li> &nbsp;
                                <li> @Html.ActionLink("Course", "IndexCourse", "UCRMS", null, new { @class = "btn-info " })</li>&nbsp;
                                <li> @Html.ActionLink("Teacher", "IndexTeacher", "UCRMS", null, new { @class = "btn-info " })</li>&nbsp;
                                <li> @Html.ActionLink("Assigned Courses", "IndexCourseAssign", "UCRMS", null, new { @class = "btn-info " })</li>&nbsp;
                                <li> @Html.ActionLink("Course Stat", "IndexCourseStat", "UCRMS", null, new { @class = "btn-info " })</li>&nbsp;
                                <li> @Html.ActionLink("Semester", "SemesterIndex", "Provider", null, new { @class = "btn-info " })</li>&nbsp;
                                <li> @Html.ActionLink("Designation", "IndexDesignation", "Provider", null, new { @class = "btn-info " })</li>&nbsp;
                            </ul>

                        </div>
                    </div>
                </nav>
            </div>
            <br />

            <div class="row">
                <div class="container body-content">
                    @*<div class="col-md-2">
                            <div class="row-offcanvas row-offcanvas-left">
                                <div id="sidebar" class="sidebar-offcanvas">
                                    <ul class="nav nav-pills nav-justified">
                                        <li class="active">@Html.ActionLink("Department Information", "Index", "UCRMS")</li>
                                        <li class="active">@Html.ActionLink("Show Department", "ShowDepartment", "Department")</li>
                                        <li class="active">@Html.ActionLink("Course Information", "Index", "Course")</li>
                                        <li class="active">@Html.ActionLink("Teacher Information", "Index", "Teacher")</li>
                                        <li class="active">@Html.ActionLink("Student Information", "Index", "Student")</li>
                                        <li class="active">@Html.ActionLink("Assign Course to Teacher", "Index", "AssignCourseToTeacher")</li>
                                        <li class="active">@Html.ActionLink("Room Allocation", "Index", "Class")</li>
                                        <li class="active">@Html.ActionLink("Course Statistics", "ShowCourses", "Course")</li>

                                        <li class="active"><a href="#">Section</a></li>
                                        <li class="active"><a href="#">Section</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                    @RenderBody()
                    @RenderSection("Scripts", required: false)
                </div>
            </div>
            <hr />

            <div class="row">
                    <footer class="col-lg-12">
                        <p>&copy; @DateTime.Now.Year -University Course and Result Management System</p>
                    </footer>
                </div>
        </div>

        <div class="row">
            <footer class="col-lg-12">
                <p>&copy; @DateTime.Now.Year -University Course and Result Management System</p>
            </footer>
        </div>
    </body>
    </html>*@


<!DOCTYPE html>
<html lang="en">
<head>
    <!-- META SECTION -->
    <title>@ViewBag.Title - University Course and Result Management System</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <link rel="icon" href="favicon.ico" type="image/x-icon" />
    <!-- END META SECTION -->
    <!-- CSS INCLUDE -->
    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/css/theme-default.css" rel="stylesheet" />
    <!-- EOF CSS INCLUDE -->
</head>
<body>
    <!-- START PAGE CONTAINER -->
    <div class="page-container">

        <!-- START PAGE SIDEBAR -->
        <div class="page-sidebar">
            <!-- START X-NAVIGATION -->
            <ul class="x-navigation">
                <li class="xn-logo">
                    @Html.ActionLink("UCRMS", "Index", "Home")
                </li>
                <li class="xn-profile">
                    <a href="#" class="profile-mini">
                        <img src="~/Content/img/campaign.jpg" alt="John Doe" />
                    </a>
                </li>
                <li class="xn-title">MENUS</li>
                <li class="xn-openable">
                    <a href="#"><span class="fa fa-files-o"></span> <span class="xn-text">Sub MENUS</span></a>
                    <ul class="nav nav-pills navbar-left">
                        <li class="active">@Html.ActionLink("Department", "Index", "UCRMS")</li>
                        <li class="active">@Html.ActionLink("Course", "IndexCourse", "UCRMS")</li>
                        <li class="active">@Html.ActionLink("Teacher", "IndexTeacher", "UCRMS")</li>
                        <li class="active">@Html.ActionLink("Student", "IndexStudent", "UCRMS")</li>
                        <li class="active">@Html.ActionLink("Assign Course to Teacher", "IndexCourseAssign", "UCRMS")</li>
                        <li class="active">@Html.ActionLink("Room Allocation", "IndexAllocateRoom", "UCRMS")</li>
                        <li class="active">@Html.ActionLink("Course Statistics", "IndexCourseStat", "UCRMS")</li>
                        <li class="active">@Html.ActionLink("Enroll", "IndexEnrollCourse", "UCRMS")</li>
                        <li class="active">@Html.ActionLink("Result", "IndexStudentResult", "UCRMS")</li>
                        <li class="active"><a href="#">Section</a></li>
                    </ul>
                </li>
                <li class="xn-openable">
                    <a href="#"><span class="fa fa-files-o"></span> <span class="xn-text">Settings</span></a>
                    <ul class="nav nav-pills navbar-left">
                        <li class="active">@Html.ActionLink("Designation", "IndexDesignation", "Provider")</li>
                        <li class="active">@Html.ActionLink("Semester", "SemesterIndex", "Provider")</li>
                        <li class="active">@Html.ActionLink("Room", "IndexRoom", "Provider")</li>
                    </ul>
                </li>
            </ul>
            <!-- END X-NAVIGATION -->
        </div>
        <!-- END PAGE SIDEBAR -->
        <!-- PAGE CONTENT -->
        <div class="page-content">

            <!-- START X-NAVIGATION VERTICAL -->
            <ul class="x-navigation x-navigation-horizontal x-navigation-panel">
                <!-- TOGGLE NAVIGATION -->
                <li class="xn-icon-button">
                    <a href="#" class="x-navigation-minimize"><span class="fa fa-dedent"></span></a>
                </li>
                <!-- END TOGGLE NAVIGATION -->
                <!-- SIGN OUT -->
                <li class="xn-icon-button pull-right">
                    <a href="#" class="mb-control" data-box="#mb-signout"><span class="fa fa-sign-out"></span></a>
                </li>
                <!-- END SIGN OUT -->
            </ul>
            <!-- END X-NAVIGATION VERTICAL -->
            <!-- START BREADCRUMB -->
            <ul class="breadcrumb">
                <li><a href="#">Home</a></li>
                <li class="active">Dashboard</li>
            </ul>
            <!-- END BREADCRUMB -->
            <!-- PAGE CONTENT WRAPPER -->
            <div class="page-content-wrap">

                @RenderBody()

            </div>

            <!-- END PAGE CONTENT WRAPPER -->

            <footer class="offset-3 fixed-bottom pull-right">
                <p style="font-weight: bold">&copy; @DateTime.Now.Year -University Course and Result Management System</p>
            </footer>
        </div>

        <!-- END PAGE CONTENT -->
    </div>

    <!-- END PAGE CONTAINER -->
    <!-- MESSAGE BOX-->
    <div class="message-box animated fadeIn" data-sound="alert" id="mb-signout">
        <div class="mb-container">
            <div class="mb-middle">
                <div class="mb-title"><span class="fa fa-sign-out"></span> Log <strong>Out</strong> ?</div>
                <div class="mb-content">
                    <p>Are you sure you want to log out?</p>
                    <p>Press No if youwant to continue work. Press Yes to logout current user.</p>
                </div>
                <div class="mb-footer">
                    <div class="pull-right">
                        <a href="pages-login.html" class="btn btn-success btn-lg">Yes</a>
                        <button class="btn btn-default btn-lg mb-control-close">No</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- END MESSAGE BOX-->
    <!-- START SCRIPTS -->
    <!-- START PLUGINS -->
    <script type="text/javascript" src="~/Content/js/jquery.min.js"></script>
    <script type="text/javascript" src="~/Content/js/jquery-ui.min.js"></script>
    <script type="text/javascript" src="~/Content/js/bootstrap.min.js"></script>
    <script type='text/javascript' src='~/Content/js/bootstrap-datepicker.js'></script>
    <!-- END PLUGINS -->
    <!-- START THIS PAGE PLUGINS-->
    <script type='text/javascript' src='~/Content/js/icheck.min.js'></script>
    <script type="text/javascript" src="~/Content/js/jquery.mCustomScrollbar.min.js"></script>
    <script type="text/javascript" src="~/Content/js/scrolltopcontrol.js"></script>

    <script type="text/javascript" src="~/Content/js/raphael-min.js"></script>
    @*<script type="text/javascript" src="~/Content/js/morris.min.js"></script>
        <script type="text/javascript" src="~/Content/js/d3.v3.js"></script>
        <script type="text/javascript" src="~/Content/js/plugins/owl/owl.carousel.min.js"></script>*@

    <script type="text/javascript" src="~/Content/js/moment.min.js"></script>
    <script type="text/javascript" src="~/Content/js/daterangepicker.js"></script>
    <!-- END THIS PAGE PLUGINS-->
    <!-- START TEMPLATE -->
    <script type="text/javascript" src="~/Content/js/settings.js"></script>

    <script type="text/javascript" src="~/Content/js/plugins.js"></script>
    <script type="text/javascript" src="~/Content/js/actions.js"></script>

    <!-- Sweet Alert -->
    <script src="~/Content/js/sweetalert2.js"></script>
    @*<script type="text/javascript" src="~/Content/js/demo_dashboard.js"></script>*@
    <!-- END TEMPLATE -->
    <!-- END SCRIPTS -->

    @RenderSection("Scripts", required: false)
@Html.Partial("_FlashMessage")
</body>
</html>